---
- include_tasks: pre.yml

- name: Configure advanced resource
  include_tasks: advanced.yml
  vars:
    resource_parent: /cib/configuration/resources
    resource: "{{ pcmk_resource }}"
  run_once: true

- include_tasks: post.yml
